### ISSUE TITLE
No such file or directory (os error 2)', src/screen/unix.rs:250:23

### ISSUE THREAD

**Issue by magnetophon** [rschmitt/heatseeker#43]
When I compile 1.7.1 on NixOS unstable I get this when I run it:

```
 ls | hs
thread 'main' panicked at 'Spawn failed: No such file or directory (os error 2)', src/screen/unix.rs:250:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Spawn failed: No such file or directory (os error 2)', src/screen/unix.rs:250:23
stack backtrace:
   0:     0x55d90cd17504 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd5cf01a6458823ce
   1:     0x55d90cd361cd - core::fmt::write::h239984b34be80164
   2:     0x55d90cd15405 - std::io::Write::write_fmt::h71b3597bde52e201
   3:     0x55d90cd1a7e5 - std::panicking::default_hook::{{closure}}::h22b55119be64c15e
   4:     0x55d90cd1a520 - std::panicking::default_hook::hb52d14bb75b54309
   5:     0x55d90cd1aee5 - std::panicking::rust_panic_with_hook::hc671c362d83d7750
   6:     0x55d90cd1aa82 - std::panicking::continue_panic_fmt::h65e4009de34f6bc6
   7:     0x55d90cd1a9dc - std::panicking::begin_panic_fmt::h3ee1dd8002c2d90b
   8:     0x55d90ccf7e28 - hs::screen::unix::Terminal::stty::hd71a89a1bdf00198
   9:     0x55d90ccf8385 - <hs::screen::unix::Terminal as core::ops::drop::Drop>::drop::h345868f7de696340
  10:     0x55d90ccf454c - core::ptr::real_drop_in_place::h50fc56ce1563076b
  11:     0x55d90ccf777f - hs::screen::unix::UnixScreen::open_screen::ha34cf2a7491e9c91
  12:     0x55d90cce8d4a - hs::main::h591dcdb950c07157
  13:     0x55d90ccee6b3 - std::rt::lang_start::{{closure}}::hffae13e0b28b56eb
  14:     0x55d90cd1a913 - std::panicking::try::do_call::haa65fe754e1236a4
  15:     0x55d90cd268aa - __rust_maybe_catch_panic
  16:     0x55d90cd1b326 - std::rt::lang_start_internal::h182449fd1250c1b3
  17:     0x55d90cceb762 - main
  18:     0x7f21ef9aab8e - __libc_start_main
  19:     0x55d90cce519a - _start
  20:                0x0 - <unknown>
thread panicked while panicking. aborting.
[1]    26423 done                                        ls --color=tty |
       26424 illegal hardware instruction (core dumped)  hs
```

**Comment by rschmitt** [comment]
This looks like a duplicate of https://github.com/rschmitt/heatseeker/issues/42, except for the "illegal hardware instruction" part. Can you try compiling v1.7.0 instead?

**Comment by magnetophon** [comment]
In the meantime, heatseeker has been packaged for nixos, and works perfectly.
